### ISSUE TITLE
Death Korps IA5-6 Companies

### ISSUE THREAD

**Issue by Florian-DELRIEU** [Florian-DELRIEU/Warhammer40k-BSdata#28]
All issues below are raise to accord the DK Catalogue with the IA5 and IA6 companies descriptions
## TODO
- [x] Line Infantry can have to 10 Platoon
- [x] Platoon commander can have heavy weapon
- [x] Grenadier can't have centaur (si plus de 5 soldats mais en même temps un centaure ne peut pas acceuillir plus de soldat en transport les garder ou pas ?)
- add Trojan 
  - [ ] ammo  - _IA1 v2_
  - [ ] comm - _not found_
- [ ] add Atlas - IA1 v2

## bug reports
- [ ] ![Capture d’écran 2022-01-22 à 21 11 07](https://user-images.githubusercontent.com/47951736/150653986-ddfa205d-6a92-4322-97b7-97eb194ae593.png)
